### ISSUE TITLE
Not decerialised

### ISSUE THREAD

**Issue by flolep2607** [wopian/hibari#555]
The info aren't showed because it's not decerialised.
![image](https://user-images.githubusercontent.com/24566964/73873860-b9350800-4852-11ea-9fb1-08fcf92eb261.png)

**Comment by wopian** [comment]
The info doesn't show because it was never implementated in this version. The warnings in the console are from loading the anime API without any attributes listed in the JSON:API client I used in 2016 - something which led me to creating the `kitsu` nom package for a better lightweight JSON:API client.

I'm currently working on a branch as part of my university work this year that has this done.
